"""Fine-tune MediaPipe Face Landmarker with prepared landmark images.

The training and validation directories should be generated by
``prepare_dataset.py``. Each directory must contain images and JSON files with
16 landmark annotations.
"""

import argparse

from mediapipe_model_maker import face_landmarker


def parse_args():
    parser = argparse.ArgumentParser(description="Fine-tune a Face Landmarker model")
    parser.add_argument("--model_path", required=True, help="Path to the base face_landmarker.task file")
    parser.add_argument("--train_dir", required=True, help="Directory with training images and annotations")
    parser.add_argument("--validation_dir", required=True, help="Directory with validation images and annotations")
    parser.add_argument("--output_dir", required=True, help="Directory to save the fine-tuned model")
    parser.add_argument("--epochs", type=int, default=50, help="Number of fine-tuning epochs")
    parser.add_argument("--batch_size", type=int, default=8, help="Batch size for training")
    return parser.parse_args()


def main():
    args = parse_args()

    train_data = face_landmarker.Dataset.from_folder(args.train_dir)
    validation_data = face_landmarker.Dataset.from_folder(args.validation_dir)

    hparams = face_landmarker.HParams(
        export_dir=args.output_dir,
        epochs=args.epochs,
        batch_size=args.batch_size,
        base_options=face_landmarker.BaseOptions(model_asset_path=args.model_path),
    )

    options = face_landmarker.FaceLandmarkerOptions(hparams=hparams)

    model = face_landmarker.FaceLandmarker.create(
        train_data=train_data,
        validation_data=validation_data,
        options=options,
    )

    model.evaluate(validation_data)
    model.export_model()


if __name__ == "__main__":
    main()
